/**
 * all Actions which the app can handle
 */

export const SELECT_BANDWIDTH_TYP = 'SELECT_BANDWIDTH_TYP'
export const SELECT_LOAD_SECONDS = 'SELECT_LOAD_SECONDS'
export const CALCULATE_BUDGET = 'CALCULATE_BUDGET'
export const REQUEST_LIBRARY = 'REQUEST_LIBRARY'
export const RECEIVE_LIBRARY = 'RECEIVE_LIBRARY'