/**
 * all Actions which the app can handle
 */

export const SELECT_BANDWIDTH_TYP = 'SELECT_BANDWIDTH_TYP'
export const SELECT_LOAD_SECONDS = 'SELECT_LOAD_SECONDS'
export const CALCULATE_BUDGET = 'CALCULATE_BUDGET'
export const HANDLE_SEARCH_INPUT = 'HANDLE_SEARCH_INPUT'
export const HANDLE_SEARCH_REQUEST = 'HANDLE_SEARCH_REQUEST'