/**
 * all Actions which the app can handle
 */

export const SELECT_BANDWIDTH_TYP = 'SELECT_BANDWIDTH_TYP'
export const SELECT_LOAD_SECONDS = 'SELECT_LOAD_SECONDS'
export const CALCULATE_BUDGET = 'CALCULATE_BUDGET'
export const HANDLE_SEARCH_INPUT = 'HANDLE_SEARCH_INPUT'
export const HANDLE_SEARCH_REQUEST = 'HANDLE_SEARCH_REQUEST'
export const PROCEED_TO_NEXT_STEP = 'PROCEED_TO_NEXT_STEP'
export const PROCEED_TO_PREVIOUS_STEP = 'PROCEED_TO_PREVIOUS_STEP'
export const OPEN_LIBRARY_DIALOG = 'OPEN_LIBRARY_DIALOG'
export const CLOSE_LIBRARY_DIALOG = 'CLOSE_LIBRARY_DIALOG'
export const TOGGLE_LIBRARY = 'TOGGLE_LIBRARY'
export const ADD_TO_ACTUAL_BUDGET = 'ADD_TO_ACTUAL_BUDGET'
export const HANDLE_SELECTED_LIBRARY_FILTER = 'HANDLE_SELECTED_LIBRARY_FILTER'